// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

pub enum FbsFooOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct FbsFoo<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for FbsFoo<'a> {
  type Inner = FbsFoo<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> FbsFoo<'a> {
  pub const VT_NAME: flatbuffers::VOffsetT = 4;
  pub const VT_A: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    FbsFoo { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args FbsFooArgs<'args>
  ) -> flatbuffers::WIPOffset<FbsFoo<'bldr>> {
    let mut builder = FbsFooBuilder::new(_fbb);
    builder.add_a(args.a);
    if let Some(x) = args.name { builder.add_name(x); }
    builder.finish()
  }


  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(FbsFoo::VT_NAME, None)}
  }
  #[inline]
  pub fn a(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(FbsFoo::VT_A, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for FbsFoo<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<i32>("a", Self::VT_A, false)?
     .finish();
    Ok(())
  }
}
pub struct FbsFooArgs<'a> {
    pub name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub a: i32,
}
impl<'a> Default for FbsFooArgs<'a> {
  #[inline]
  fn default() -> Self {
    FbsFooArgs {
      name: None,
      a: 0,
    }
  }
}

pub struct FbsFooBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> FbsFooBuilder<'a, 'b> {
  #[inline]
  pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(FbsFoo::VT_NAME, name);
  }
  #[inline]
  pub fn add_a(&mut self, a: i32) {
    self.fbb_.push_slot::<i32>(FbsFoo::VT_A, a, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> FbsFooBuilder<'a, 'b> {
    let start = _fbb.start_table();
    FbsFooBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<FbsFoo<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for FbsFoo<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("FbsFoo");
      ds.field("name", &self.name());
      ds.field("a", &self.a());
      ds.finish()
  }
}
pub enum FbsBarOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct FbsBar<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for FbsBar<'a> {
  type Inner = FbsBar<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> FbsBar<'a> {
  pub const VT_NAME: flatbuffers::VOffsetT = 4;
  pub const VT_FOO: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    FbsBar { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args FbsBarArgs<'args>
  ) -> flatbuffers::WIPOffset<FbsBar<'bldr>> {
    let mut builder = FbsBarBuilder::new(_fbb);
    if let Some(x) = args.foo { builder.add_foo(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    builder.finish()
  }


  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(FbsBar::VT_NAME, None)}
  }
  #[inline]
  pub fn foo(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<FbsFoo<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<FbsFoo>>>>(FbsBar::VT_FOO, None)}
  }
}

impl flatbuffers::Verifiable for FbsBar<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<FbsFoo>>>>("foo", Self::VT_FOO, false)?
     .finish();
    Ok(())
  }
}
pub struct FbsBarArgs<'a> {
    pub name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub foo: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<FbsFoo<'a>>>>>,
}
impl<'a> Default for FbsBarArgs<'a> {
  #[inline]
  fn default() -> Self {
    FbsBarArgs {
      name: None,
      foo: None,
    }
  }
}

pub struct FbsBarBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> FbsBarBuilder<'a, 'b> {
  #[inline]
  pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(FbsBar::VT_NAME, name);
  }
  #[inline]
  pub fn add_foo(&mut self, foo: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<FbsFoo<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(FbsBar::VT_FOO, foo);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> FbsBarBuilder<'a, 'b> {
    let start = _fbb.start_table();
    FbsBarBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<FbsBar<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for FbsBar<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("FbsBar");
      ds.field("name", &self.name());
      ds.field("foo", &self.foo());
      ds.finish()
  }
}
